# Generated by Django 3.0.5 on 2020-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='contact',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
