# Generated by Django 3.1.3 on 2020-11-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
